### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by eugene-tx200** [Alex07Wind/uamed_update#1]
Hi,
I found string:
`public String imgdir = "/home/alex/Downloads/top/fall2016/";`
Better to keep hardcoded settings like this in a separate config file.
BR:Eugene

**Comment by Alex07Wind** [comment]
Hi! I keep private settings in class connoption in this project. I don't
think that settings is very compomise my security it is file on my local
machine not on server host.
14 июля 2016 г. 20:42 пользователь "Yevgen" <notifications@github.com>
написал:
